### PR TITLE
Implement import helper and change methods to async

### PR DESCRIPTION
**Pull request by samtsai**
This approach does not work in my project locally yet, still tinkering

- [x] Update and fix tests
- [ ] Can we avoid having to upgrade node to `18.19.x` or `20.x.x`?
- [ ] fix CI

### CODE REVIEW

**Comment by bahmutov** [comment]
ughh, I really would prefer not to switch from sync to async, it would be a big breaking change

**Comment by samtsai** [comment]
> ughh, I really would prefer not to switch from sync to async, it would be a big breaking change

I figured so. I'm trying to focus on the sync version but both approaches are a pain...

**Comment by samtsai** [comment]
I could at least get it working asynchronously though I understand this would be a major breaking change.

**Comment by samtsai** [comment]
I may have figured out a simpler way 😄 

https://github.com/bahmutov/find-cypress-specs/pull/233

**Pull request closed without merging**
